Repository EmoTrak/EmoTrak-FrontEnd, pull requests merged in 2023-04, with the labels that each got.

#6 feat: 로그인 UI (#1)
  src/data/type/d1.ts
  src/data/type/d2.ts
  src/features/login/components/LoginForm.tsx
  src/features/login/components/Tutorial.tsx
  src/pages/Login.tsx
Labels: feature

#13 Feat/chart
  package.json
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
  yarn.lock
Labels: enhancement

#14 Feat/register UI feature
  src/data/type/d3.ts
  src/features/login/components/LoginForm.tsx
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useEmailValidation.tsx
  src/features/signup/hooks/useNicknameValidation.tsx
  src/features/signup/hooks/usePasswordCheck.tsx
  src/features/signup/hooks/useSignup.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: enhancement, feature

#19 Feat/calendar
  src/assets/emoticon/테스트용.png
  src/components/Flex.tsx
  src/data/routes/urls.ts
  src/data/type/d1.ts
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/Sidebar.tsx
  src/pages/Home.tsx
Labels: enhancement

#25 Feat/canvas
  src/data/type/d3.ts
  src/features/post/components/Canvas.tsx
  src/features/post/components/Palette.tsx
  src/features/post/hooks/useEraser.tsx
  src/features/post/hooks/usePen.tsx
  src/pages/DrawingPost.tsx
Labels: enhancement, feature

#26 feat: 아이콘 컴포넌트화 #23
  src/assets/emoticon/1_Fun.svg
  src/assets/emoticon/2_Smile.svg
  src/assets/emoticon/3_Calm.svg
  src/assets/emoticon/4_Sad.svg
  src/assets/emoticon/5_Angry.svg
  src/assets/emoticon/6_Cry.svg
  src/components/Icon/EmoticonIcons.tsx
  src/components/Icon/getEmoticonIcon.ts
Labels: enhancement, design

#29 fix: emoticon 코드 오류 수정 #28
  src/components/Icon/getEmoticonIcon.ts
Labels: bug, enhancement, design

#35 feat: 이미지파일 업로드 기능 #21
  src/features/imagepost/components/Image.tsx
  src/features/imagepost/components/ImagePostPage.tsx
  src/pages/ImagePost.tsx
Labels: feature

#33 Feat/form
  src/assets/star.svg
  src/components/Icon/EmoticonIcons.tsx
  src/components/Icon/Star.tsx
  src/components/Icon/getEmoticonIcon.ts
  src/features/post/hooks/useInput.tsx
  src/pages/DrawingPost.tsx
Labels: bug, enhancement, feature

#41 feat: 카카오 소셜로그인 기능구현 완료 #40
  src/data/routes/urls.ts
  src/features/login/components/LoginForm.tsx
  src/features/login/hooks/useLogin.tsx
  src/pages/RedirectKakao.tsx
  src/shared/Router.tsx
Labels: enhancement

#43 feat: chart 서버 연결 후 데이터 출력 #36
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: feature

#45 feat: 상세페이지 ui 구현 완료 (수정기능 제외) #42
  src/data/queryKeys/keys.ts
  src/features/detail/hooks/useDelete.tsx
  src/features/detail/hooks/useEdit.tsx
  src/pages/Detail.tsx
  src/pages/Edit.tsx
  src/shared/Router.tsx
Labels: enhancement

#48 feat: 관리자 페이지 컴포넌트 완료 (기능 제외) #44
  src/features/Admin/AdminNavbar.tsx
  src/features/Admin/AdminPost.tsx
  src/features/Admin/AdminUser.tsx
  src/pages/Admin.tsx
  src/shared/Router.tsx
Labels: feature

#50 feat: 글작성(사진, 그림) 서버연결 완료, 수정기능 완료 #46
  src/data/routes/urls.ts
  src/features/detail/hooks/useEdit.tsx
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/features/post/hooks/usePreview.ts
  src/pages/Detail.tsx
  src/pages/DrawingPost.tsx
  src/pages/Edit.tsx
  src/pages/ImagePost.tsx
Labels: enhancement

#51 Feat/calendar
  src/assets/emoticon/7_none.svg
  src/components/Icon/getEmoticonIcon.ts
  src/components/Modal.tsx
  src/data/queryKeys/keys.ts
  src/data/type/d1.ts
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/Sidebar.tsx
  yarn.lock
Labels: feature

#56 design: header, footer UI 및 라우터 구현 #49
  src/App.tsx
  src/assets/emoticon/footer.svg
  src/assets/이모트랙 로고.svg
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/pages/Chart.tsx
  src/pages/Members.tsx
  src/shared/Router.tsx
Labels: feature, design

#59 feat: 마이페이지 UI #58
  src/features/mypage/hooks/useAuth.tsx
  src/pages/Mypage.tsx
  src/shared/Router.tsx
Labels: enhancement, feature

#62 fix: header 버튼 오류 수정 #61
  src/data/routes/urls.ts
  src/features/login/hooks/useLogin.tsx
  src/layouts/Header.tsx
Labels: bug

#64 fix : 카카오로그인 쿠키 버그 수정 #63
  src/data/queryKeys/keys.ts
  src/pages/RedirectKakao.tsx
Labels: bug

#69 fix: Chart 데이터출력 및 차트 커스텀 #60
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: bug, feature, design

#74 Fix/input maxlength
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/login/components/LoginForm.tsx
  src/features/signup/components/SignupForm.tsx
  yarn.lock
Labels: bug

#72 fix: chart colors 수정
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  yarn.lock
Labels: bug, design

#75 feat: 마이페이지 기능 서버측 오류로 유저정보 불러오기 미완성. 변경기능 완성#70
  src/features/mypage/hooks/useAuth.tsx
  src/features/mypage/hooks/useChangeNickname.ts
  src/features/mypage/hooks/useChangePassword.ts
  src/pages/Mypage.tsx
Labels: enhancement

#77 design: 패럴럭스 스크롤 기본 틀잡기 #76
  src/assets/EmoTrakLogo.svg
  src/features/login/components/LoginForm.tsx
  src/features/login/components/Tutorial.tsx
  src/layouts/Header.tsx
  src/pages/Login.tsx
Labels: enhancement, feature

#79 fix: Chart 페이지 type 수정 및 로직수정 #78
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: bug

#81 Feat/community
  package.json
  src/data/routes/urls.ts
  src/data/type/d1.ts
  src/features/community/hooks/useEmoSelect.tsx
  src/features/community/hooks/useInfinite.tsx
  src/pages/Community.tsx
  yarn.lock
Labels: feature

#83 fix: 회원가입 버그- 정규식수정 #80
  src/data/type/d3.ts
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useNicknameValidation.tsx
  src/features/signup/hooks/usePasswordCheck.tsx
  src/pages/Signup.tsx
Labels: bug

#85 fix: 로그인 페이지 기능 수정 #84
  src/features/login/hooks/useLogin.tsx
  src/pages/RedirectKakao.tsx
Labels: bug, enhancement

#87 design: 패럴럭스스크롤 윗부분 아이콘변경 #86
  src/assets/EmoTrakLogo.svg
  src/assets/logo/IconLeft.svg
  src/assets/logo/IconMain.svg
  src/assets/logo/IconRight.svg
  src/assets/logo/IconText.svg
  src/assets/tutorial/1-LandingMain.png
  src/assets/tutorial/2-LandingCal.png
  src/assets/tutorial/3-LandingPost.png
  src/assets/tutorial/4-LandingGraph.png
  src/features/login/components/Tutorial.tsx
Labels: design

#90 Feat/post details
  src/features/imagepost/components/ImagePostPage.tsx
  src/features/post/components/Canvas.tsx
  src/features/post/components/Palette.tsx
  src/features/post/components/PenTool.tsx
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/pages/Detail.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImagePost.tsx
Labels: bug, enhancement

#91 feat: 관리자페이지 댓글, 게시물 테이블 생성 #89
  src/data/queryKeys/keys.ts
  src/features/Admin/AdminPost.tsx
  src/features/Admin/AdminUser.tsx
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminNavbar.tsx
  src/features/admin/components/AdminPost.tsx
  src/pages/Admin.tsx
  src/shared/Router.tsx
Labels: feature

#94 fix: 글 수정페이지 버그 #93
  src/data/queryKeys/keys.ts
  src/features/detail/hooks/useEdit.tsx
  src/pages/Detail.tsx
  src/pages/Edit.tsx
Labels: bug

#97 Feat/community detail
  src/data/type/d1.ts
  src/features/community/components/Comment.tsx
  src/features/community/components/CommentEdit.tsx
  src/features/community/hooks/useAddComment.tsx
  src/features/community/hooks/useAddCommunityDetail.tsx
  src/features/community/hooks/useDeleteComment.tsx
  src/features/community/hooks/useUpdateComment.tsx
  src/features/detail/hooks/useDelete.tsx
  src/lib/api/user.ts
  src/pages/Community.tsx
  src/pages/CommunityDetail.tsx
Labels: feature

#101 feat: 소셜로그인 - 네이버 #96
  src/data/routes/urls.ts
  src/features/login/components/LoginForm.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/shared/Router.tsx
Labels: enhancement

#102 신고게시물 공유 해제 및 신고댓글 삭제 #100
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
Labels: feature

#104 fix: 수정기능 버그 - 사진수정없이 수정 #103
  src/features/detail/hooks/useEdit.tsx
Labels: bug

#106 [fix] chart 데이터 클릭 시 렌더링 안되는 현상 수정 #105
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
Labels: bug

#108 fix: 그림판 브러시 툴 안보이는 오류 수정 #107
  src/features/post/components/Canvas.tsx
  src/pages/DrawingPost.tsx
Labels: bug

#111 feat: chart select 버튼으로 변경
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: feature

#112 Feat/community detail
  src/components/Modal.tsx
  src/data/type/d1.ts
  src/features/community/components/Comment.tsx
  src/features/community/components/CommentEdit.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/LikeComment.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/Report.tsx
  src/features/community/hooks/useAddCommunityDetail.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/pages/CommunityDetail.tsx
Labels: feature

#113 comment: 글작성 주석 추가 #109
  src/features/post/components/Canvas.tsx
  src/features/post/hooks/useEraser.ts
  src/features/post/hooks/useInput.ts
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/features/post/hooks/usePreview.ts
  src/pages/DrawingPost.tsx
  src/pages/ImagePost.tsx
Labels: documentation

#115 feat: 달력 '오늘'날짜 이후엔 글작성 막기 #114
  src/features/diary/components/Calendar.tsx
  src/pages/CommunityDetail.tsx
Labels: enhancement

#117 refactor: type 분리 및 토큰유무에 따른 페이지가드 #116
  src/data/type/d2.ts
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Admin.tsx
  src/pages/Chart.tsx
Labels: enhancement

#122 Design/gloval style
  src/assets/EmoTrakLogo.svg
  src/assets/emoticon/star.svg
  src/assets/logo/EmoTrakLogo.png
  src/assets/tutorial/IconLeft.svg
  src/assets/tutorial/IconMain.svg
  src/assets/tutorial/IconRight.svg
  src/assets/tutorial/IconText.svg
  src/components/GlobalStyle.tsx
  src/components/Icon/Star.tsx
  src/features/login/components/Tutorial.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/pages/Community.tsx
  src/shared/Router.tsx
Labels: design

#121 refactor: admin, chart 커스텀 훅 분리 #120
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartData.tsx
  src/pages/Chart.tsx
Labels: enhancement

#125 fix: chart에 데이터가 없을 때 문구 띄우기 #124
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartData.tsx
  src/pages/Chart.tsx
Labels: enhancement

#130 fix: 회원가입 페이지 버그 #129
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useSignup.tsx
Labels: bug, enhancement

#133 fix: 마이페이지 버그 수정 #131
  src/features/mypage/hooks/useAuth.tsx
  src/features/mypage/hooks/useWithdrawal.tsx
  src/pages/Mypage.tsx
Labels: bug, enhancement, feature

#132 fix: chart 월 slider, select 구현 및 커스텀 훅분리
  src/components/Modal.tsx
  src/data/type/d2.ts
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartFn.tsx
  src/pages/Chart.tsx
Labels: bug, enhancement

#136 fix: 글작성 페이지 버그 #135
  src/data/routes/urls.ts
  src/features/post/components/Canvas.tsx
  src/features/post/hooks/usePen.ts
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
  src/shared/Router.tsx
Labels: bug, enhancement

#138 fix: 상세페이지 버그 수정 #137
  src/features/detail/components/DeleteConfirmModal.tsx
  src/pages/Detail.tsx
Labels: bug

#143 Fix/community
  src/components/subModal.tsx
  src/data/type/d1.ts
  src/features/community/components/PostDate.tsx
  src/features/community/components/Report.tsx
  src/pages/CommunityDetail.tsx
Labels: bug

#145 fix: 관리자페이지 axios url 변경 및 신고된 게시글 신고삭제 기능 #144
  src/data/type/d2.ts
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
Labels: bug

#147 feat: 그림판 수정 페이지 #139
  src/features/detail/hooks/useEdit.tsx
  src/features/post/components/Canvas.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/Mypage.tsx
Labels: bug, enhancement

#152 refactor: 로그 삭제 #150
  src/features/mypage/hooks/useAuth.tsx
  src/features/post/components/Contents.tsx
  src/pages/Detail.tsx
Labels: documentation

#149 fix: 헤더 로그아웃 시 리렌더링 #148
  src/features/admin/components/AdminComment.tsx
  src/layouts/Header.tsx
  src/pages/Chart.tsx
Labels: bug

#151 Fix/community
  src/data/type/d1.ts
  src/features/community/components/Boards.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/PostDate.tsx
  src/features/community/components/Report.tsx
  src/features/community/hooks/useEmoSelect.tsx
  src/features/community/hooks/useInfinite.tsx
  src/pages/CommunityDetail.tsx
Labels: bug

#156 design: footer 디자인 변경 #155
  src/layouts/Footer.tsx
  src/pages/Chart.tsx
Labels: design

#157 Design/parallax scroll
  src/assets/tutorial/1-LandingMain.png
  src/assets/tutorial/1_Tutorial.png
  src/assets/tutorial/1_Tutorial_bottom.png
  src/assets/tutorial/1_Tutorial_top.png
  src/assets/tutorial/2_Icon_1.png
  src/assets/tutorial/2_Icon_2.png
  src/assets/tutorial/2_Icon_3.png
  src/assets/tutorial/2_Icon_4.png
  src/assets/tutorial/2_Icon_5.png
  src/assets/tutorial/2_Sun_1.png
  src/assets/tutorial/2_Sun_2.png
  src/assets/tutorial/2_Text_1.png
  src/assets/tutorial/3_Icon_1.png
  src/assets/tutorial/3_Icon_2.png
  src/assets/tutorial/3_Icon_3.png
  src/assets/tutorial/3_Icon_4.png
  src/assets/tutorial/3_Icon_5.png
  src/assets/tutorial/3_Icon_6.png
  src/assets/tutorial/4-LandingGraph.png
  src/assets/tutorial/4_Calender.png
  src/assets/tutorial/4_Drawing.png
  src/assets/tutorial/4_Graph.png
  src/assets/tutorial/4_GraphTitle.svg
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-34-24-1.png
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-34-24-2.png
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-41-43 001.png
  src/features/login/TutorialStyle.tsx
  src/features/login/components/Tutorial.tsx
Labels: design

#162 fix: 로그인 리프레시 토큰 관련 쿠키 셋팅 수정(일시적) #161
  src/features/login/hooks/useLogin.tsx
Labels: bug

#160 design: chart 월 클릭 모달 스타일변경 및 이전, 다음달 버튼 생성 #159
  src/features/chart/hooks/useChartFn.tsx
  src/pages/Chart.tsx
Labels: enhancement, design

#165 feat: 리프레시토큰 #158
  src/features/login/hooks/useLogin.tsx
  src/lib/api/user.ts
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
Labels: enhancement, feature

#167 fix: 로그아웃 로직수정 #166
  src/layouts/Header.tsx
Labels: bug

#169 design: 사진 일기 작성css #168
  src/components/Checkbox.tsx
  src/components/Icon/Star.tsx
  src/features/post/components/Canvas.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
Labels: design

#171 design: 그림일기 작성페이지 css #170
  src/assets/Drawing/Ball Point Pen.png
  src/assets/Drawing/Erase.png
  src/assets/Drawing/Reboot.png
  src/features/post/components/PenTool.tsx
  src/features/post/hooks/usePen.ts
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
Labels: design

#173 Feat/community detail
  src/components/PageNation.tsx
  src/features/community/components/Comment.tsx
  src/features/community/hooks/useAddCommunityDetail.tsx
  src/layouts/Footer.tsx
  src/layouts/Layout.tsx
  src/pages/CommunityDetail.tsx
Labels: enhancement

#176 design/diary
  src/features/diary/components/Calendar.tsx
Labels: design

#177 design/diary-sidebar
  src/features/diary/components/Sidebar.tsx
Labels: design

#178 design: 마이페이지 css #175
  src/features/mypage/components/InputList.tsx
  src/pages/Mypage.tsx
Labels: design

#181 fix: 리프레시토큰 버그 수정 #180
  src/lib/api/user.ts
Labels: bug

#185 fix: 인터셉터 수정 #180
  src/lib/api/user.ts
Labels: bug

#186 design: 로그인 css #179
  src/assets/Social/Google.svg
  src/assets/Social/Kakao.svg
  src/assets/Social/Naver.svg
  src/assets/Texts/Login.svg
  src/assets/Texts/Signup_1.svg
  src/features/login/components/LoginForm.tsx
  src/features/mypage/components/InputList.tsx
  src/pages/DrawingPost.tsx
  src/pages/Mypage.tsx
Labels: design

#182 fix: 달력 날짜오류 불필요한 서버요청 오류해결 #174
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/CalendarEmo.tsx
  src/features/diary/components/Sidebar.tsx
Labels: bug

#187 design: 메인페이지 css #172
  src/features/community/components/Boards.tsx
Labels: design

#193 feat: 소셜로그인 - google #189
  src/data/queryKeys/keys.ts
  src/data/routes/urls.ts
  src/features/login/components/LoginForm.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectNaver.tsx
  src/shared/Router.tsx
Labels: enhancement, good first issue, feature

#192 fix: 페이지네이션 총 페이지 5개이하 ui수정 #191
  src/components/PageNation.tsx
Labels: bug

#195 fix: 댓글 신고하기 버튼 오류 수정 #194
  src/data/type/d1.ts
  src/features/community/components/Comment.tsx
  src/pages/CommunityDetail.tsx
Labels: bug

#197 design: 공유페이지 css 수정 #196
  src/features/community/components/Boards.tsx
Labels: design

#199 design: 회원가입 css #198
  src/assets/Texts/Signup.svg
  src/features/login/components/LoginForm.tsx
  src/features/mypage/components/InputList.tsx
  src/features/signup/components/SignupForm.tsx
Labels: design

#204 fix: 그림판 수정기능 버그 #202
  src/features/detail/hooks/useEdit.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
Labels: bug

#205 fix: 공유페이지 스크롤 리셋현상 #190
  src/features/community/components/Boards.tsx
  src/features/community/hooks/useInfinite.tsx
Labels: bug

#210 design: 공유페이지 css #209
  src/data/type/d1.ts
  src/features/community/components/Boards.tsx
  src/features/community/hooks/useEmoSelect.tsx
  src/features/community/hooks/useInfinite.tsx
Labels: design

#207 chore: vercel 배포 관련 파일 추가 #206
  vercel.json
Labels: build

#212 design: 상세페이지 css #203
  src/data/type/d1.ts
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/LikeComment.tsx
  src/features/community/hooks/useDeleteComment.tsx
  src/features/community/hooks/useUpdateComment.tsx
  src/features/post/components/Canvas.tsx
  src/pages/Chart.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
Labels: design

#214 design: 메인페이지 css, 모달컴포넌트 수정 #211
  src/components/Modal.tsx
  src/components/subModal.tsx
  src/data/type/d1.ts
  src/features/community/components/Report.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/CalendarEmo.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
Labels: design

#213 feat: 관리자 페이지 신고게시물 페이지네이션 #142
  src/components/PageNation.tsx
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/pages/CommunityDetail.tsx
Labels: feature

#218 design: 소셜로그인 버튼 수정 #188
  src/assets/Social/Google.svg
  src/assets/Social/Kakao.svg
  src/assets/Social/Naver.svg
  src/features/login/components/LoginForm.tsx
Labels: design

#219 feat: Protected Route 적용하기 #118
  src/data/routes/urls.ts
  src/data/type/d2.ts
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/pages/Admin.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
Labels: enhancement, feature

#220 Feat/button components
  src/components/Button.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/diary/components/Calendar.tsx
  src/features/login/components/LoginForm.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
  src/pages/Mypage.tsx
Labels: enhancement, design

#225 chore: console.log 지우기 #224
  src/components/Checkbox.tsx
  src/components/Icon/Star.tsx
  src/components/Icon/getEmoticonIcon.ts
  src/data/type/d1.ts
  src/data/type/d3.ts
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/features/chart/hooks/useChartFn.tsx
  src/features/community/components/Boards.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/PostDate.tsx
  src/features/community/hooks/useEmoSelect.tsx
  src/features/community/hooks/useInfinite.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/detail/hooks/useEdit.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/DiaryStyle.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/login/components/LoginForm.tsx
  src/features/login/components/Tutorial.tsx
  src/features/mypage/components/InputList.tsx
  src/features/mypage/hooks/useAuth.tsx
  src/features/post/components/Canvas.tsx
  src/features/post/components/Contents.tsx
  src/features/post/components/Palette.tsx
  src/features/post/hooks/useEraser.ts
  src/features/post/hooks/useInput.ts
  src/features/post/hooks/usePen.ts
  src/features/signup/components/SignupForm.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/lib/api/user.ts
  src/pages/Chart.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
  src/pages/Login.tsx
  src/pages/Members.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/pages/Signup.tsx
  src/shared/ProtectedRouter.tsx
Labels: documentation

#227 build: 패키지파일 변경 #226
  package.json
Labels: bug, build

#229 chore: JSX.Element 삭제 및 request header Access-Control-Allow-Origin 삭제…
  src/App.tsx
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminNavbar.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartData.tsx
  src/features/chart/hooks/useChartFn.tsx
  src/features/community/components/Boards.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/PostDate.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/imagepost/components/Image.tsx
  src/features/mypage/hooks/useAuth.tsx
  src/features/post/components/Canvas.tsx
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/features/signup/components/SignupForm.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/lib/api/guest.ts
  src/lib/api/user.ts
  src/pages/Admin.tsx
  src/pages/Chart.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/Home.tsx
  src/pages/ImagePost.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: documentation

#231 chore: hide source map #230
  package.json
Labels: build

#234 fix: s3 그림일기 기존 이미지 불러오기 오류 #233
  src/lib/api/user.ts
Labels: bug

#235 fix/community
  src/features/diary/components/Calendar.tsx
  src/features/post/hooks/usePost.ts
  src/shared/Router.tsx
Labels: bug

#241 fix: 글수정 버그 수정 #240
  src/pages/DrawEdit.tsx
  src/pages/ImageEdit.tsx
Labels: bug

#243 fix: 토큰이 있을시 로그인페이지 이동막기 #242
  src/data/routes/urls.ts
  src/data/type/d2.ts
  src/features/login/hooks/useLogin.tsx
  src/layouts/Header.tsx
  src/pages/Login.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
Labels: documentation

#245 fix: 로그인이 안되있을 시 로그인 공유페이지 이외 이동 막기 #244
  src/features/diary/components/Calendar.tsx
  src/shared/ProtectedRouter.tsx
Labels: bug

#247 [design] 상세페이지, 공유상세페이지 css, 감정점수 별 이미지로 바꾸기 #246
  src/components/Button.tsx
  src/components/Icon/Star.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/post/components/Canvas.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
Labels: design

#249 build: vercel dns 설정 관련 코드 추가 #248
  public/index.html
Labels: documentation, build

#251 fix: 권한 없는 사용자에게 수정, 삭제버튼 안보이게 막기 #250
  src/features/community/components/Comment.tsx
  src/pages/CommunityDetail.tsx
Labels: bug

#253 fix: 별 컴포넌트 수정 #252
  src/components/Icon/Star.tsx
Labels: bug

#254 fix: 글 수정 페이지 버그#240
  src/features/detail/hooks/useEdit.tsx
  src/features/post/hooks/usePost.ts
  src/pages/DrawEdit.tsx
  src/pages/ImageEdit.tsx
Labels: bug

#258 doc: 개인정보 처리방침 페이지 추가 #256
  src/data/routes/urls.ts
  src/layouts/Footer.tsx
  src/pages/PrivacyPolicy.tsx
  src/shared/Router.tsx
Labels: documentation

#257 fix: 로그인 안될 시 홈으로 이동 막기 #255
  src/features/diary/components/Calendar.tsx
Labels: bug

#264 design: 그림일기 계속하기 버튼 수정 #263
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
Labels: design

#261 fix: 로그인 안될 시 달력페이지 이동 막기 #260
  src/features/diary/components/Calendar.tsx
Labels: bug

#266 docs: 개인정보 처리방침 수정 #265
  src/pages/PrivacyPolicy.tsx
Labels: documentation

#271 fix: users 인터셉터 수정 #270
  src/lib/api/user.ts
Labels: bug

#276 design: Theme 파일 추가 #275
  src/App.css
  src/App.test.tsx
  src/components/Button.tsx
  src/components/Checkbox.tsx
  src/components/GlobalStyle.tsx
  src/components/Icon/Star.tsx
  src/components/Modal.tsx
  src/components/PageNation.tsx
  src/components/subModal.tsx
  src/data/type/style.d.ts
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminNavbar.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/community/components/Boards.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/LikeComment.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/Report.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/CalendarEmo.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/mypage/components/InputList.tsx
  src/features/post/components/Canvas.tsx
  src/features/post/components/Contents.tsx
  src/features/post/components/Palette.tsx
  src/features/post/components/PenTool.tsx
  src/features/signup/components/SignupForm.tsx
  src/index.css
  src/index.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/logo.svg
  src/pages/Chart.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/utils/theme.ts
Labels: design

#278 fix: 차트페이지 모달 수정 #277
  src/data/type/d2.ts
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartData.tsx
  src/features/chart/hooks/useChartFn.tsx
  src/pages/Chart.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
Labels: documentation, enhancement

#281 Design/parallax scroll detail
  src/assets/tutorial/1_Tutorial.png
  src/assets/tutorial/1_Tutorial.webp
  src/assets/tutorial/1_Tutorial_bottom.png
  src/assets/tutorial/1_Tutorial_bottom.webp
  src/assets/tutorial/1_Tutorial_top.png
  src/assets/tutorial/1_Tutorial_top.webp
  src/assets/tutorial/2_Icon_1.png
  src/assets/tutorial/2_Icon_1.webp
  src/assets/tutorial/2_Icon_2.png
  src/assets/tutorial/2_Icon_2.webp
  src/assets/tutorial/2_Icon_3.png
  src/assets/tutorial/2_Icon_3.webp
  src/assets/tutorial/2_Icon_4.png
  src/assets/tutorial/2_Icon_4.webp
  src/assets/tutorial/2_Icon_5.png
  src/assets/tutorial/2_Icon_5.webp
  src/assets/tutorial/2_Sun_1.png
  src/assets/tutorial/2_Sun_1.webp
  src/assets/tutorial/2_Sun_2.png
  src/assets/tutorial/2_Sun_2.webp
  src/assets/tutorial/2_Text_1.png
  src/assets/tutorial/2_Text_1.webp
  src/assets/tutorial/3_Icon_1.png
  src/assets/tutorial/3_Icon_1.webp
  src/assets/tutorial/3_Icon_1_left.webp
  src/assets/tutorial/3_Icon_2.png
  src/assets/tutorial/3_Icon_2.webp
  src/assets/tutorial/3_Icon_3.png
  src/assets/tutorial/3_Icon_3.webp
  src/assets/tutorial/3_Icon_4.png
  src/assets/tutorial/3_Icon_4.webp
  src/assets/tutorial/3_Icon_5.png
  src/assets/tutorial/3_Icon_5.webp
  src/assets/tutorial/3_Icon_6.png
  src/assets/tutorial/3_Icon_6.webp
  src/assets/tutorial/4_Calendar.webp
  src/assets/tutorial/4_Calender.png
  src/assets/tutorial/4_Drawing.png
  src/assets/tutorial/4_Drawing.webp
  src/assets/tutorial/4_Graph.png
  src/assets/tutorial/4_Graph.webp
  src/assets/tutorial/4_GraphTitle.svg
  src/assets/tutorial/4_GraphTitle.webp
  src/assets/tutorial/IconLeft.svg
  src/assets/tutorial/IconLeft.webp
  src/assets/tutorial/IconMain.svg
  src/assets/tutorial/IconMain.webp
  src/assets/tutorial/IconRight.svg
  src/assets/tutorial/IconRight.webp
  src/assets/tutorial/IconText.svg
  src/assets/tutorial/IconText.webp
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-34-24-1.png
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-34-24-2.png
  src/assets/tutorial/KakaoTalk_Photo_2023-04-12-19-41-43 001.png
  src/assets/tutorial/green.webp
  src/features/login/TutorialStyle.tsx
  src/features/login/components/Tutorial.tsx
Labels: design

#284 design: calendar 반응형웹 디자인 #280
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/CalendarEmo.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/Sidebar.tsx
  src/lib/api/user.ts
  src/utils/theme.ts
Labels: design

#286 design: header, footer 반응형 웹 적용하기 #285
  src/assets/mobileMenubar/Calendar.png
  src/assets/mobileMenubar/Combo Chart.png
  src/assets/mobileMenubar/Logout.png
  src/assets/mobileMenubar/Paste.png
  src/features/diary/components/Calendar.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/layouts/MobileMenubar.tsx
Labels: design

#288 design: 공유페이지 반응형 웹 적용하기 #287
  src/features/community/components/Boards.tsx
  src/features/community/hooks/useInfinite.tsx
Labels: design

#290 design: 차트페이지 반응형 웹 구현 #279
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: design

#298 design: Header 디자인 수정 #297
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
Labels: design

#293 design: 상세페이지 모바일 뷰 적용 #292
  src/components/GlobalStyle.tsx
  src/pages/Detail.tsx
Labels: design

#301 Design/mobile landing
  src/assets/tutorial/4_Calendar.webp
  src/assets/tutorial/4_Calender.webp
  src/assets/tutorial/4_Drawing.webp
  src/assets/tutorial/4_Graph.webp
  src/assets/tutorial/5_Calender.webp
  src/assets/tutorial/5_Canvas.webp
  src/assets/tutorial/5_Graph.webp
  src/data/type/style.d.ts
  src/features/login/components/Landing.tsx
  src/features/login/components/Tutorial.tsx
  src/pages/Login.tsx
  src/utils/theme.ts
Labels: design

#304 Design/calendar
  src/components/Modal.tsx
  src/components/subModal.tsx
  src/features/community/components/Report.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/pages/CommunityDetail.tsx
Labels: design

#307 Design/mobile login
  src/assets/Social/Google.svg
  src/assets/Social/Google.webp
  src/assets/Social/GoogleMobile.webp
  src/assets/Social/Kakao.svg
  src/assets/Social/Kakao.webp
  src/assets/Social/KakaoMobile.webp
  src/assets/Social/Naver.svg
  src/assets/Social/Naver.webp
  src/assets/Social/NaverMobile.webp
  src/features/login/components/LoginForm.tsx
  src/features/mypage/components/InputList.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
Labels: design

#309 feat : PWA 적용 시도 1차 #308
  package.json
  public/index.html
  public/server.js
  src/index.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
  yarn.lock
Labels: enhancement, feature

#311 fix: PWA - install 버튼 안뜨는 버그 #310
  public/index.html
  public/manifest.json
  public/server.js
  src/index.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
Labels: bug

#314 design: 차트 페이지 모바일 토글 및 차트 배경 색 수정 #313
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: design

#315 design: 로그인 페이지 사이즈 수정 #312
  src/features/login/components/Landing.tsx
  src/features/login/components/LoginForm.tsx
  src/features/mypage/components/InputList.tsx
  src/pages/Mypage.tsx
Labels: design

#317 design: 라우터 및 헤더 푸터 수정 #316
  src/data/type/d2.ts
  src/features/chart/hooks/useChartFn.tsx
  src/layouts/Footer.tsx
  src/layouts/Header.tsx
  src/layouts/Layout.tsx
  src/pages/Chart.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
Labels: design

#319 design: 달력페이지, 공유상세페이지, 글작성페이지 모바일뷰 수정 #318
  src/features/community/components/Boards.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/Report.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/pages/CommunityDetail.tsx
  src/pages/ImagePost.tsx
Labels: design

#323 fix: 로고 클릭 이벤트 수정 #322
  src/layouts/Header.tsx
Labels: enhancement

#321 design: 회원가입 css #320
  src/features/diary/components/Calendar.tsx
  src/features/login/components/LoginForm.tsx
  src/features/signup/components/SignupForm.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/pages/Signup.tsx
Labels: design

#325 fix: service worker 캐시 로직 수정 #324
  src/service-worker.ts
Labels: bug

#327 fix: service-worker 오류 수정 #326
  src/index.tsx
Labels: bug

#329 Refactor/type module
  src/components/Button.tsx
  src/components/Checkbox.tsx
  src/components/Flex.tsx
  src/components/Icon/EmoticonIcons.tsx
  src/components/Icon/Star.tsx
  src/components/Modal.tsx
  src/components/subModal.tsx
  src/data/queryKeys/keys.ts
  src/data/type/d1.ts
  src/data/type/d2.ts
  src/data/type/d3.ts
  src/data/type/type.ts
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/chart/hooks/useChartFn.tsx
  src/features/community/components/Boards.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/LikeComment.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/PostDate.tsx
  src/features/community/components/Report.tsx
  src/features/community/hooks/useAddComment.tsx
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/detail/hooks/useEdit.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/CalendarEmo.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/login/TutorialStyle.tsx
  src/features/login/components/Landing.tsx
  src/features/login/components/LoginForm.tsx
  src/features/login/hooks/useLogin.tsx
  src/features/mypage/components/InputList.tsx
  src/features/post/components/Canvas.tsx
  src/features/post/components/Contents.tsx
  src/features/post/components/Palette.tsx
  src/features/post/components/PenTool.tsx
  src/features/post/hooks/useEraser.ts
  src/features/post/hooks/useInput.ts
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useSignup.tsx
  src/layouts/MobileMenubar.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
  src/pages/Mypage.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
  src/utils/cookies.ts
  tsconfig.json
Labels: refactor

#333 refactor: 달력 페이지 리팩토링 #332
  src/assets/emoticon/테스트용.png
  src/components/Modal.tsx
  src/features/admin/styles/AdminPostStyle.ts
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/ClickModalPost.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/MonthSelect.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/diary/hooks/useDate.ts
  src/features/diary/hooks/useGetDiary.ts
  src/features/diary/styles/CalendarStyle.ts
  src/features/diary/styles/MiniCalendarStyle.ts
  src/features/diary/styles/MonthSelectStyle.ts
Labels: refactor

#337 refactor: admin 페이지 #336
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminNavbar.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/features/admin/styles/AdminContentStyle.ts
  src/features/admin/styles/AdminNavbarStyle.ts
  src/features/admin/styles/AdminStyle.ts
Labels: refactor

#342 refactor: detail & community detail #341
  src/components/GlobalStyle.tsx
  src/data/type/style.d.ts
  src/features/chart/components/BarChart.tsx
  src/features/chart/components/PieChart.tsx
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/LikeComment.tsx
  src/features/community/components/LikePost.tsx
  src/features/community/components/PostDate.tsx
  src/features/community/components/Report.tsx
  src/features/community/hooks/useAddCommunityDetail.tsx
  src/features/community/hooks/useDeleteComment.tsx
  src/features/community/hooks/useLikeComment.tsx
  src/features/community/hooks/useLikePost.ts
  src/features/community/hooks/useReport.ts
  src/features/community/hooks/useUpdateComment.tsx
  src/features/community/styles/CommentStyle.ts
  src/features/community/styles/CommunityDetailStyle.ts
  src/features/community/styles/CreateCommentStyle.ts
  src/features/community/styles/LikeCommentStyle.ts
  src/features/community/styles/ReportStyle.ts
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/detail/hooks/useDelete.ts
  src/features/detail/hooks/useDelete.tsx
  src/features/detail/hooks/useEdit.ts
  src/features/detail/hooks/useGetDetail.ts
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/utils/theme.ts
Labels: refactor

#344 feat: 회원가입시 이메일 인증추가 #340
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useEmailValidation.tsx
  src/features/signup/hooks/useNicknameValidation.tsx
Labels: feature

#345 Refactor/post
  src/features/detail/hooks/useEdit.ts
  src/features/detail/hooks/useGetDetail.ts
  src/features/post/components/Canvas.tsx
  src/features/post/components/Contents.tsx
  src/features/post/components/EmoScore.tsx
  src/features/post/components/Palette.tsx
  src/features/post/components/PenTool.tsx
  src/features/post/components/PostInput.tsx
  src/features/post/components/StarScore.tsx
  src/features/post/hooks/useEraser.ts
  src/features/post/hooks/useInput.ts
  src/features/post/hooks/usePen.ts
  src/features/post/hooks/usePost.ts
  src/features/post/styles/DrawingStyle.ts
  src/features/post/styles/ImageStyle.ts
  src/features/post/styles/PaletteStyle.ts
  src/features/post/styles/PenToolStyle.ts
  src/lib/api/user.ts
  src/pages/DrawEdit.tsx
  src/pages/DrawingPost.tsx
  src/pages/ImageEdit.tsx
  src/pages/ImagePost.tsx
Labels: refactor

#348 Refactor/login signup
  src/assets/Drawing/Ball Point Pen.png
  src/assets/Drawing/Erase.png
  src/assets/Drawing/Reboot.png
  src/assets/Social/Google.svg
  src/assets/Social/Google.webp
  src/assets/Social/Kakao.svg
  src/assets/Social/Kakao.webp
  src/assets/Social/Naver.svg
  src/assets/Social/Naver.webp
  src/assets/tutorial/5_Calender.webp
  src/assets/tutorial/5_Canvas.webp
  src/assets/tutorial/5_Graph.webp
  src/assets/tutorial/5_Graph_1.webp
  src/assets/tutorial/5_Graph_2.webp
  src/assets/tutorial/5_Landing.webp
  src/data/routes/urls.ts
  src/data/type/type.ts
  src/features/login/components/Landing.tsx
  src/features/login/components/LoginForm.tsx
  src/features/login/components/Tutorial.tsx
  src/features/login/hooks/useLogin.tsx
  src/features/login/styles/LandingStyle.ts
  src/features/login/styles/LoginFormStyle.ts
  src/features/login/styles/TutorialStyle.ts
  src/features/mypage/components/InputList.tsx
  src/features/mypage/hooks/useWithdrawal.tsx
  src/features/mypage/styles/InputListStyle.ts
  src/features/mypage/styles/MypageStyle.ts
  src/features/signup/components/SignupForm.tsx
  src/features/signup/hooks/useEmailValidation.tsx
  src/features/signup/hooks/useNicknameValidation.tsx
  src/features/signup/hooks/usePasswordCheck.tsx
  src/features/signup/hooks/useSignup.tsx
  src/features/signup/styles/SignupFormStyle.ts
  src/pages/DrawingPost.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
Labels: refactor

#350 refactor: layout #349
  src/data/routes/urls.ts
  src/features/mypage/styles/InputListStyle.ts
  src/features/mypage/styles/MypageStyle.ts
  src/layouts/LayoutStyle.ts
  src/layouts/MobileMenubar.tsx
  src/pages/Mypage.tsx
  src/shared/ProtectedRouter.tsx
Labels: refactor

#352 refactor: board #351
  src/features/community/components/Boards.tsx
  src/features/community/hooks/useEmoSelect.tsx
  src/features/community/hooks/useInfinite.tsx
Labels: refactor

#355 fix: 차트 모바일 토글 버튼 클릭 이벤트 수정 #353
  src/features/chart/components/PieChart.tsx
  src/pages/Chart.tsx
Labels: bug

#357 fix: 그림판 터치이벤트 #346
  src/data/routes/urls.ts
  src/features/post/components/Canvas.tsx
  src/features/post/hooks/useEraser.ts
  src/features/post/hooks/usePen.ts
  src/features/post/styles/DrawingStyle.ts
Labels: bug, enhancement

#358 feat: 달력 모바일 화면에서 화면깨짐 수정 #354
  src/components/Modal.tsx
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/MiniCalendar.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/diary/styles/CalendarStyle.ts
  src/features/diary/styles/MiniCalendarStyle.ts
  src/features/diary/styles/SidebarStyle.ts
  src/layouts/Header.tsx
  src/layouts/LayoutStyle.ts
  src/layouts/MobileMenubar.tsx
Labels: design

#362 fix: 회원탈퇴시 회원 캐시삭제 #360
  src/App.tsx
  src/features/mypage/hooks/useWithdrawal.tsx
Labels: bug

#364 design: 마이페이지 디자인 #363
  src/features/mypage/styles/MypageStyle.ts
  src/pages/Mypage.tsx
Labels: design

#368 feat: 404페이지 구현 #356
  src/features/chart/components/BarChart.tsx
  src/pages/Loading.tsx
  src/pages/NotFound.tsx
Labels: feature

#370 feat: 코드스플리팅 #369
  src/components/Error.tsx
  src/components/Loading.tsx
  src/features/admin/components/AdminComment.tsx
  src/features/admin/components/AdminPost.tsx
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/features/community/components/Boards.tsx
  src/features/detail/hooks/useGetDetail.ts
  src/features/diary/components/Calendar.tsx
  src/features/diary/hooks/useGetDiary.ts
  src/pages/Chart.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/ImageEdit.tsx
  src/pages/Mypage.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/shared/Router.tsx
Labels: enhancement, feature

#372 feat: 에러핸들러 #371
  src/data/queryKey/keys.ts
  src/data/routes/urls.ts
  src/features/admin/hooks/useAdminComment.tsx
  src/features/admin/hooks/useAdminPost.tsx
  src/features/chart/hooks/useChartData.tsx
  src/features/community/components/Boards.tsx
  src/features/community/hooks/useAddComment.tsx
  src/features/community/hooks/useAddCommunityDetail.tsx
  src/features/community/hooks/useDeleteComment.tsx
  src/features/community/hooks/useInfinite.tsx
  src/features/community/hooks/useReport.ts
  src/features/community/hooks/useUpdateComment.tsx
  src/features/detail/hooks/useDelete.ts
  src/features/detail/hooks/useEdit.ts
  src/features/detail/hooks/useGetDetail.ts
  src/features/diary/components/Calendar.tsx
  src/features/diary/components/Sidebar.tsx
  src/features/diary/hooks/useGetDiary.ts
  src/features/mypage/hooks/useAuth.tsx
  src/features/mypage/hooks/useWithdrawal.tsx
  src/features/post/hooks/usePost.ts
  src/hooks/useError.ts
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/lib/api/user.ts
  src/pages/Chart.tsx
  src/pages/CommunityDetail.tsx
  src/pages/Detail.tsx
  src/pages/DrawEdit.tsx
  src/pages/ImageEdit.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/utils/logout.ts
Labels: enhancement, feature

#374 design: reset css #373
  public/index.html
  public/reset.css
  src/assets/fonts/JalnanOTF00.woff
  src/assets/fonts/KyoboHand.woff
  src/assets/fonts/Pretendard-Regular.woff
Labels: design

#378 Fix/error code
  src/data/type/type.ts
  src/hooks/useError.ts
  src/lib/api/user.ts
Labels: bug
