Repository EmoTrak/EmoTrak-FrontEnd, pull requests merged in 2023-05, with the labels that each got.

#462 fix/community detail
  src/features/community/components/Comment.tsx
  src/features/community/components/CreateComment.tsx
  src/features/community/components/Report.tsx
  src/features/community/styles/CommentStyle.ts
  src/features/community/styles/ReportStyle.ts
  src/pages/CommunityDetail.tsx
Labels: bug, design

#466 Fix/post feedback
  src/components/Icon/Star.tsx
  src/data/type/type.ts
  src/features/post/components/Canvas.tsx
  src/features/post/components/Palette.tsx
  src/features/post/components/PenTool.tsx
  src/features/post/components/PostInput.tsx
  src/features/post/components/StarScore.tsx
  src/features/post/styles/DrawingStyle.ts
  src/pages/ImagePost.tsx
Labels: bug, design

#467 Fix/community
  src/data/type/type.ts
  src/features/community/components/Boards.tsx
  src/features/community/components/HoverImage.tsx
  src/features/community/hooks/useInfinite.tsx
  src/features/community/styles/CommunityStyle.ts
  src/features/detail/components/DeleteConfirmModal.tsx
  src/features/detail/hooks/useDelete.ts
  src/layouts/LayoutStyle.ts
  src/pages/Community.tsx
  src/pages/Detail.tsx
Labels: bug, feature

#469 feat: 공유게시판 throttling 적용 #468
  src/layouts/Header.tsx
  src/pages/Community.tsx
Labels: feature

#471 Fix/login feedback
  src/data/routes/urls.ts
  src/data/type/type.ts
  src/features/login/components/LoginForm.tsx
  src/features/login/hooks/useLogin.tsx
  src/features/signup/components/SignupForm.tsx
  src/hooks/useError.ts
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/pages/Guide.tsx
  src/pages/Login.tsx
  src/pages/Mypage.tsx
  src/pages/RedirectGoogle.tsx
  src/pages/RedirectKakao.tsx
  src/pages/RedirectNaver.tsx
  src/shared/ProtectedRouter.tsx
  src/shared/Router.tsx
Labels: bug, enhancement

#475 fix: 메인페이지 유저피드백 반영 #470
  src/features/diary/styles/CalendarStyle.ts
  src/pages/Home.tsx
Labels: bug

#474 feat: 그린 그림 저장하기 #458
  src/features/detail/hooks/useSave.ts
  src/features/detail/styles/DetailStyle.ts
  src/pages/Detail.tsx
Labels: enhancement, design

#477 fix:튜토리얼페이지 #476
  src/components/GlobalStyle.tsx
  src/features/login/styles/TutorialStyle.ts
Labels: bug, design

#481 fix:뒤로가기 방지 protected route #480
  src/lib/api/user.ts
  src/pages/Detail.tsx
  src/pages/Login.tsx
  src/shared/ProtectedRoute.tsx
  src/shared/Router.tsx
  src/utils/error.ts
Labels: bug

#483 fix: 삭제된 페이지 진입막기 #482
  src/features/community/components/Report.tsx
  src/features/community/hooks/useAddCommunityDetail.ts
  src/features/detail/hooks/useGetDetail.ts
Labels: bug

#491 refactor: 로그아웃 유틸함수 폴더위치 변경 #490
  src/layouts/Header.tsx
  src/pages/Mypage.tsx
  src/utils/error.ts
  src/utils/logout.ts
Labels: enhancement

#493 Docs/write readme
  README.md
  src/assets/logo/archi.webp
  src/layouts/Header.tsx
  src/pages/Mypage.tsx
  src/utils/error.ts
  src/utils/logout.ts
Labels: documentation

#497 docs: readme 트러블슈팅 추가 #495
  README.md
  src/assets/logo/cardNews.webp
  src/shared/ProtectedRoute.tsx
Labels: documentation

#498 [docs] readme 트러블슈팅 추가 #495
  README.md
  src/assets/logo/cardNews.webp
  src/shared/ProtectedRoute.tsx
Labels: documentation

#501 fix: 라우터 수정 #500
  src/data/type/type.ts
  src/features/community/components/Report.tsx
  src/shared/ProtectedRoute.tsx
  src/shared/Router.tsx
Labels: bug

#503 fix/router
  src/data/type/type.ts
  src/features/community/components/Report.tsx
  src/shared/ProtectedRoute.tsx
  src/shared/Router.tsx
Labels: bug

#509 fix: 공유상세페이지 뒤로가기버튼 수정 #508
  src/pages/CommunityDetail.tsx
Labels: bug

#511 [remove] pwa 관련 코드 삭제 #510
  public/index.html
  public/manifest.json
  src/features/community/components/Report.tsx
  src/index.tsx
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/pages/CommunityDetail.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
Labels: refactor

#512 [remove] pwa 관련 코드 삭제 #510
  public/index.html
  public/manifest.json
  src/features/community/components/Report.tsx
  src/index.tsx
  src/layouts/Header.tsx
  src/layouts/MobileMenubar.tsx
  src/service-worker.ts
  src/serviceWorkerRegistration.ts
Labels: refactor

#514 [fix] 배포 오류 수정 #513
  public/manifest.json
  public/splash.webp
Labels: bug
